#KTOR-936 Migrate to explicit api mode(part 8)
ktorio/ktor pull request #2059
Opened 2020-09-09 15:07 UTC by e5l

2020-09-10 08:21 UTC, cy6erGn0m commented on build.gradle
> +            explicitApi()
So it becomes error, right?

2020-09-10 08:21 UTC, e5l commented on build.gradle
> +            explicitApi()
Yep

2020-09-10 08:56 UTC, cy6erGn0m commented on build.gradle
> +    "ktor-server-test-host",
Why is the test host excluded?

2020-09-10 10:40 UTC, e5l commented on build.gradle
> +    "ktor-server-test-host",
To exclude suites

2020-09-10 17:20 UTC, Stexxe requested changes

2020-09-10 17:20 UTC, Stexxe commented on build.gradle
> +def ignoreExplicitApi = [
This name is better suited for a method, not for a list of things. I suggest  `DisabledExplicitApiModeProjects` or something shorter.

2020-09-10 17:20 UTC, Stexxe commented on build.gradle
> +                manifes.readLines().each {
Typo?

2020-09-11 07:14 UTC, e5l commented on build.gradle
> +                manifes.readLines().each {
yep. thanks for catching

2020-09-11 08:57 UTC, Stexxe approved these changes

2020-09-11 10:31 UTC, merged