Remove api check from ktor-server-test-host module
ktorio/ktor pull request #2089
Opened 2020-09-23 16:59 UTC by rsinukov

**Motivation**
It is a test only module

2020-09-23 17:06 UTC, cy6erGn0m commented
Unfortunately, it contains a testing API (functions like `withTestApplication` and the test host implementation). We probably need to split the module into two

2020-09-24 09:34 UTC, rsinukov commented
@cy6erGn0m thanks, I split the module into two

2020-09-28 06:18 UTC, e5l requested changes
LGTM, except minor problems

2020-09-28 06:18 UTC, e5l commented on gradle/compatibility.gradle
> +        'ktor-server-test-host-suites',
maybe we can name it `ktor-server-test-sutes`?

2020-09-28 06:18 UTC, e5l commented on ktor-server/ktor-server-test-host-suites/build.gradle
> +    jvmTestApi project(path: ':ktor-server:ktor-server-core', configuration: 'testOutput')
Can be done in a modern way:
```
kotlin.sourceSets {
    jvmMain { 
    }
    jvmTest { 
    }
}
```

2020-09-28 13:44 UTC, e5l approved these changes

2020-09-28 13:44 UTC, e5l requested changes

2020-09-28 13:44 UTC, e5l commented on ktor-server/ktor-server-test-suites/build.gradle
> +    jvmTestApi project(path: ':ktor-server:ktor-server-core', configuration: 'testOutput')
same here

2020-09-29 07:46 UTC, e5l approved these changes
Good job, lgtm

2020-09-29 10:32 UTC, merged