feat: log startup time
ktorio/ktor pull request #2093
Opened 2020-09-25 16:18 UTC by pavelgordon

**Subsystem**
Server, ktor-server-host-common

**Motivation**
There is an issue https://github.com/ktorio/ktor/issues/2006. After consideration, I decided that it might be useful to log startup time.

Also, I wanted to contribute to open source, and this issue looks like a good first issue to start with.

**Solution**
`init` block in `BaseApplicationEngine` looks like a perfect place to log the information about startup time along with host and port(which were present already). 

On receiving the `ApplicationStarted` event -  the information about startup time is logged.

I know that there are other possible solutions - e.g. using StopWatch, but was not sure if bringing an additional library worth the drill. What do you think?

2020-09-26 06:58 UTC, cy6erGn0m commented
What is the minimal android sdk requited for java.time.Duration?

2020-09-26 19:28 UTC, pavelgordon commented
Yep, I had the same idea so I decided to change implementation to use System.nanoTime because java.time.Duration is available in JDK 8, and according to [this link](https://developer.android.com/reference/java/time/Duration) - from API level 26.

I removed the imports.

2020-09-29 10:41 UTC, cy6erGn0m requested changes

2020-09-29 10:41 UTC, cy6erGn0m commented on ktor-server/ktor-server-host-common/jvm/src/io/ktor/server/engine/BaseApplicationEngine.kt
> +                environment.log.info("Startup time: ${(initializeFinishedAt - initializeStartedAt) / 1_000_000} ms")
Sorry, didn't noticed that but why do we print the same message for evey connector?

2020-10-26 18:51 UTC, cy6erGn0m commented
@pavelgordon could you please also rebase it?

2021-04-11 07:47 UTC, closed without merging