Update HttpCacheEntry.kt
ktorio/ktor pull request #2102
Opened 2020-10-01 14:31 UTC by gincos

Fix crash on empty/invalid expires header

**Subsystem**
Client

**Motivation**
 #1892 .

**Solution**
Handle the case where the Expires header is empty or invalid, and return a GMTDate() as it would if such header was not present.

2020-10-01 15:01 UTC, cy6erGn0m requested changes
A test is required for different cases including missing header, empty header, blank header and some random characters

2020-10-01 15:01 UTC, cy6erGn0m commented on ktor-client/ktor-client-core/common/src/io/ktor/client/features/cache/HttpCacheEntry.kt
> +    } catch(e: Throwable) {
We definitely shouldn't simply ignore the error. I would skip missing or "blank" content but crash at an invalid content.

2020-10-01 15:26 UTC, gincos commented
@cy6erGn0m I believe the changes I included now are more representative of what you said. If it is invalid, it will throw an exception. If it is null or blank, then is handled like not present.

2020-10-01 15:42 UTC, cy6erGn0m commented
> @cy6erGn0m I believe the changes I included now are more representative of what you said. If it is invalid, it will throw an exception. If it is null or blank, then it is handled like the header is not present.

Ok, that's it. Now we need to add tests and clean the codestyle a bit. You can simply reformat the block.

2020-10-01 16:29 UTC, cy6erGn0m commented
@gincos Sorry for mess but I've just read the RFC and found the following: 

> A cache recipient MUST interpret invalid date formats, especially the
   value "0", as representing a time in the past (i.e., "already
   expired").

So we need to ignore parsing errors as you did at first, but just without KNPE (because it is expensive).

2020-10-11 15:12 UTC, gincos commented
I believe the current version correctly handles it? 🙂

2020-10-16 17:08 UTC, cy6erGn0m commented
@gincos yes, exactly. Now we need tests

2020-10-26 18:50 UTC, cy6erGn0m commented
@gincos we are running out of time for 1.4.2 so we'll move this patch to 1.4.3 since we still have no test

2020-10-27 08:03 UTC, cy6erGn0m commented
Ok, I've made a separate PR with a test

2020-10-27 08:03 UTC, closed without merging

2020-10-27 08:03 UTC, cy6erGn0m commented
Thanks for your help

2020-10-27 09:43 UTC, gincos commented
Sorry I could not do this in due time! And thanks for creating the tests yourself 😁