KTOR-1247 - Fix writing race condition in ByteBufferChannel
ktorio/ktor pull request #2200
Opened 2020-11-16 16:38 UTC by rsinukov

**Subsystem**
Client/Server, ByteBufferChannel

**Motivation**
[KTOR-1247](https://youtrack.jetbrains.com/issue/KTOR-1247)
Race condition:

1. writer calls `channel.writeByte` 
2. writer goes inside `setupStateForWrite` 
3. no bytes available for write -> `buffer.limit() == buffer.position()`
4. reader reads content, creates space for the writer
5. writer checks capacity in state -> success, tries to write to a preconfigured buffer that has no available space
6. crash

**Solution**
* Move setting up buffer position and limit after checking of capacity to avoid race. 
* Unified behavior of `writeByte/Short/Int/Long`
* Cleaned up some unused methods and parameters

2020-11-17 11:27 UTC, e5l requested changes
LGTM, please make some cleanup.

It's really strange that `joining` state was unused

2020-11-17 11:27 UTC, e5l commented on ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
> +    private fun doWrite(buffer: ByteBuffer, l: Long, c: RingBufferCapacity) {
`c -> capacity`
`l -> limit`

2020-11-17 11:27 UTC, e5l commented on ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
>          if (c.tryWriteExact(8)) {
please invert condition and return early

2020-11-23 09:37 UTC, e5l approved these changes
LGTM, Please fix names

2020-11-23 09:37 UTC, e5l commented on ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
> +    internal fun bytesWrittenFromSesion(buffer: ByteBuffer, capacity: RingBufferCapacity, n: Int) {
`n` could be also renamed

2020-11-23 09:37 UTC, e5l commented on ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
> +    override suspend fun writeByte(value: Byte) {
public parameter names shouldn't be renamed

2020-11-27 15:11 UTC, cy6erGn0m approved these changes

2020-11-27 15:19 UTC, merged