KTOR-1268 Fix `readRemaining` lost bytes
ktorio/ktor pull request #2214
Opened 2020-11-24 12:56 UTC by e5l

Fixes [KTOR-1268](https://youtrack.jetbrains.com/issue/KTOR-1268)

2020-11-24 17:20 UTC, rsinukov approved these changes
LGTM
nit: should we deprecate `joinTo` and remove it in a major release if there are no usages left

2020-11-24 17:21 UTC, rsinukov requested changes
sorry, didn't mention it first. 
`DeflaterReadChannelTest.testSmallPieces` was running for 3 hours and timed out

2020-11-26 08:29 UTC, cy6erGn0m requested changes

2020-11-26 08:29 UTC, cy6erGn0m commented on ktor-io/jvm/src/io/ktor/utils/io/ByteBufferChannel.kt
> +            println("CD return 1: ${state.capacity}")
println

2020-11-26 08:29 UTC, cy6erGn0m commented on ktor-utils/jvm/test/io/ktor/tests/utils/DeflaterReadChannelTest.kt
> +            println("Step: $step")
println

2020-11-26 08:29 UTC, cy6erGn0m commented on ktor-utils/jvm/test/io/ktor/tests/utils/DeflaterReadChannelTest.kt
> +            println("Launched")
more debug stuff

2020-11-26 08:29 UTC, cy6erGn0m commented on ktor-utils/jvm/test/io/ktor/tests/utils/DeflaterReadChannelTest.kt
> +        runBlocking {
Please revert the test changes

2020-11-26 14:52 UTC, rsinukov approved these changes

2020-11-27 07:22 UTC, cy6erGn0m approved these changes

2020-11-27 13:25 UTC, merged