KTOR-1460 Switch to org.w3c.fetch
ktorio/ktor pull request #2238
Opened 2020-12-08 12:47 UTC by hfhbd

**Subsystem**
Client Core JS

**Motivation**
Currently, the JS client contains old generated definitions, because the Standard Library did not contain these definitions. Now, the Standard Library contains these definitions. https://youtrack.jetbrains.com/issue/KTOR-1460

**Solution**
Switch from old generated definitions to the Standard Library

2020-12-24 19:50 UTC, cy6erGn0m commented
@hfhbd  We definitely have some problem: a lot of errors `ReferenceError: Headers is not defined` on nodejs. Didn't investigated it yet

2021-01-08 12:25 UTC, hfhbd commented
Sorry!
@cy6erGn0m I did investigate and the `Headers` are defined in `org.w3c.fetch`, which are defined in browsers, but not on NodeJS. So I defined them using `external` and `node-fetch`, but interesting this external definitions only works with `js(IR)`, see https://github.com/hfhbd/NodeFetchKotlinJS and run `./gradlew run`, if you switch to `js` the run task will fail... 
I will create an issue on Youtrack.

2021-01-13 11:04 UTC, hfhbd commented
@cy6erGn0m Could you please rerun the TeamCity build? I added the definitions and on my MacBook, the full build with allTests(3563) runs fine, except 4 JVM StacktraceWalking tests...

2021-02-04 20:28 UTC, rsinukov commented
Hi @hfhbd,
Thanks for the contribution! Looks good, but can you rebase to the latest master, please?

2021-02-04 21:34 UTC, hfhbd commented
@rsinukov here you go.

2021-02-08 16:24 UTC, rsinukov commented
thanks @hfhbd 
In general, it looks good, but we can't merge it until the issue with the JS legacy compiler is fixed or JS IR becomes the default one.
Let's wait for the compiler team.

2021-02-08 16:38 UTC, hfhbd commented
> thanks @hfhbd
> In general, it looks good, but we can't merge it until the issue with the JS legacy compiler is fixed or JS IR becomes the default one.
> Let's wait for the compiler team.

@rsinukov which issue do you mean? https://youtrack.jetbrains.com/issue/KT-44238? I did implement a workaround for this issue. Otherwise, `Headers` on Node.JS would be still undefined and node.JS test would fail

2021-02-10 12:33 UTC, rsinukov approved these changes

2021-02-10 12:34 UTC, rsinukov commented
@hfhbd oh, sorry, I misread your previous comment. LGTM

2021-02-10 12:43 UTC, rsinukov requested changes
Oh, sorry, one more small thing

2021-02-10 12:43 UTC, rsinukov commented on ktor-client/ktor-client-core/js/src/io/ktor/client/fetch/LibDom.kt
> -public external fun fetch(input: String, init: RequestInit? = definedExternally): Promise<Response>
We can't delete declarations now, only in 2.0.0. Can you keep it, but add deprecations? Then it's ok to go to the master branch.

2021-02-10 12:51 UTC, hfhbd commented
@rsinukov That was one of my initial questions in the ticket :D
"Will this update be a breaking change? All current definitions are public but external.
ApiDump did not changed the api file, but supports the binary validator external JS definitions?"
So, public external JS declarations are counting to the API? At the end, the Kotlin declarations are "only" wrapper declarations and the underlying JS functions are still available...

2021-02-10 12:59 UTC, rsinukov commented
Yes, public external counts, because people can reference them in their code.

2021-02-10 19:41 UTC, hfhbd commented
@rsinukov Added deprecations

2021-02-11 12:47 UTC, rsinukov approved these changes
LGTM

2021-02-11 12:48 UTC, merged