Fix CIO client tunneling https through http proxy
ktorio/ktor pull request #2285
Opened 2021-01-02 12:47 UTC by PegasisForever

**Subsystem**
CIO client

**Motivation**
Fixes wrong http `CONNECT` request when tunneling https through a http proxy.
The request line should be `CONNECT $host:$port HTTP/1.1` (e.g. `CONNECT example.com:443 HTTP/1.1`)
Not `CONNECT ${url} HTTP/1.1` (e.g. `CONNECT https://example.com:443/ HTTP/1.1`)

**Related PR**
#2256

2021-01-04 18:48 UTC, rsinukov requested changes
Thanks for the contribution and fix!
Do you mind revert [this](https://github.com/ktorio/ktor/pull/2256/files#diff-18edf3fb889a9385335519e1e6676232f6c9bf580c927935a60f407267059fe8R85) change from the original PR as well?
Otherwise LGTM

2021-01-04 19:25 UTC, PegasisForever commented
Thanks, I reverted that change

2021-01-05 11:36 UTC, rsinukov approved these changes

2021-01-05 11:37 UTC, rsinukov commented
Thanks, I will merge it after it runs on CI

2021-01-05 12:33 UTC, merged