Make base name of micrometer metrics configurable
ktorio/ktor pull request #2323
Opened 2021-01-28 10:02 UTC by asevich

**Subsystem**
Server, Micrometer

**Motivation**
When Ktor service is running in the environment with services written in other frameworks like Spring Boot, having standardized metric names is important for monitoring. Static, non-configurable "ktor.http.server" base name is inconvenient and breaks existing monitoring setup or at least requires special handling for Ktor services.

**Solution**
Make it configurable

2021-02-23 07:20 UTC, asevich commented
@cy6erGn0m could you please have a look and merge or reject it?

2021-02-23 12:10 UTC, rsinukov requested changes
Hi and thanks for your contribution.
Can you please rebase on `1.6.0-eap` branch, run `./gradlew apiDump`, and commit new API files?
Otherwise, LGTM.

2021-02-23 14:30 UTC, asevich commented
well, I did my best, but I'm sometimes get confused with rebase. If that doesn't look good then I will just close this PR and open new one with 1.6.0-eap as base

2021-02-23 18:16 UTC, rsinukov commented
@asevich you need to do interactive rebase and drop all the commits that are not related. 
`git rebase -i origin/1.6.0-eap` and replace `pick` with `drop` (or just `d`) in every commit, except the one that you need.

2021-02-24 07:38 UTC, asevich commented
@rsinukov thank you for the tip! 
I think now it should be fine

2021-02-24 11:33 UTC, rsinukov requested changes
Thanks! Just a couple of things.

2021-02-24 11:33 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt
> +
checkstyle complains about this extra blank line

2021-02-24 11:33 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/api/ktor-metrics-micrometer.api
> -	public static final field activeGaugeName Ljava/lang/String;
This change is a problem. We can't have any removals in non-major versions. You need to keep old constants, but deprecate them and have some other meaningful name for new properties.

2021-02-24 11:34 UTC, rsinukov commented
Can you rebase one more time, please? We rebased `1.6.0-eap` on `main` today, so no your PR has some extra commits again.

2021-02-24 12:42 UTC, asevich commented
I've reverted changes to existing api and added new properties, but naming is a bit pain in the back. Maybe `configurableActiveGaugeName` and `configurableRequestTimerName` would be better? I'm lost here
Other thing is - I've added in every test an assertion to verify, that same gauge and timer are accessible via old and new properties, iff metricsBaseName isn't changed. I hope that was a correct thing to do

2021-02-24 17:28 UTC, rsinukov approved these changes
LGTM, just some very minor things

2021-02-24 17:28 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt
> +        val exception = assertFails {
`assertFailsWith<IllegalArgumentException> { ...`

2021-02-24 17:28 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/test/io/ktor/metrics/micrometer/MicrometerMetricsTests.kt
> +            testRegistry.assertEqualRequestTimers()
Not sure if we need it for every test. I think it's better to add an extra test that verifies new properties have an old value by default and that's it.

2021-02-24 17:28 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt
> +            "static gauge name deprecated",
`is deprecated`

2021-02-24 17:28 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt
> +            "static request time timer name deprecated",
`is deprecated`

2021-02-24 17:28 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt
> +        @Deprecated("static metrics base name deprecated", level = DeprecationLevel.WARNING)
no need to deprecate it. it's private, no one will use it anyway. But maybe rename it to `defaultBaseName`?

2021-02-26 10:24 UTC, rsinukov approved these changes

2021-02-26 10:24 UTC, rsinukov commented on ktor-features/ktor-metrics-micrometer/jvm/src/io/ktor/metrics/micrometer/MicrometerMetrics.kt
> +        public var baseName: String = Feature.defaultBaseName
the very last thing: can you add kdoc to this and other public properties, please?

2021-02-26 11:55 UTC, asevich commented
I'm not really sure where to add the kdoc, so I just did monkey copy/paste job. Please tell me, if you meant something different

2021-02-26 12:04 UTC, merged

2021-02-26 12:04 UTC, rsinukov commented
Thanks! Merged!