KTOR-1965 Add an option to ignore trailing slash in routing
ktorio/ktor pull request #2326
Opened 2021-01-30 00:04 UTC by rsinukov

**Subsystem**
Server, routing

**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-1165

**Solution**
Add parameter to `routing` function to ignore trailing slash in routing

2021-01-30 17:59 UTC, cy6erGn0m commented
Not sure if `isTrailingSlashMatters` a good name. I personally would, in opposite, name it `ignoreTrailingSlash`. But I don't insist

2021-02-01 09:55 UTC, e5l requested changes
Let's brainstorm on the parameter name. I would also check the test coverage of the routing feature

2021-02-01 09:55 UTC, e5l commented on ktor-server/ktor-server-core/api/ktor-server-core.api
> +	public final fun isTrailingSlashMatters ()Z
We need a different name for sure

2021-02-01 09:57 UTC, e5l commented
Agree with @cy6erGn0m, `ignoreTrailingSlash` is good. We also can try `allowTrailingSlashHandlers`

2021-02-01 11:02 UTC, rsinukov commented
i like @cy6erGn0m  suggestion of `ignoreTrailingSlash `

2021-02-02 14:37 UTC, e5l approved these changes

2021-02-02 14:37 UTC, e5l commented on ktor-server/ktor-server-core/jvm/src/io/ktor/routing/IgnoreTrailingSlash.kt
> +        true -> attributes.put(IgnoreTrailingSlashAttributeKey, Unit)
why not `if else`?

2021-02-02 17:06 UTC, merged