KTOR-2007 Fix running custom response validation without default one
ktorio/ktor pull request #2340
Opened 2021-02-04 14:53 UTC by rsinukov

**Subsystem**
Client

**Motivation**
[Custom response validation is not running when the default is disabled](https://youtrack.jetbrains.com/issue/KTOR-2007)

2021-02-04 15:52 UTC, Stexxe requested changes
Unit tests are missing

2021-02-04 16:26 UTC, rsinukov commented
@Stexxe don't think that it makes sense to write unit tests here. The current feature touches a lot of entities like pipelines, client, call, request, response, interceptors, etc. I don't see a value in a test that will mock them, but if we will use real ones, we will end up in the same integration test. What do you think?

2021-02-05 09:05 UTC, Stexxe commented on ktor-client/ktor-client-core/common/src/io/ktor/client/features/HttpCallValidator.kt
> +        val validators = when {
```
val defaultValidators = responseValidators.filter { it == DefaultValidator }.filter { expectSuccess }
val restValidators = responseValidators.filter { it != DefaultValidator }
(defaultValidators + restValidators).forEach { it(call.response) }
```

2021-02-05 11:56 UTC, Stexxe approved these changes

2021-02-08 14:33 UTC, e5l approved these changes

2021-02-08 15:18 UTC, merged