Fix flaky ClientSocketTest.testSelfConnect[jvm]
ktorio/ktor pull request #2356
Opened 2021-02-12 13:02 UTC by Stexxe

https://youtrack.jetbrains.com/issue/KTOR-2060

2021-02-12 13:27 UTC, cy6erGn0m requested changes
The main question is why we stopped looking for a random port?

2021-02-12 13:27 UTC, cy6erGn0m commented on ktor-network/jvm/test/io/ktor/network/sockets/tests/ClientSocketTest.kt
> +                val clientAddress = InetSocketAddress("0.0.0.0", 3333)
The fixed port will introduce one more instability point

2021-02-12 13:27 UTC, cy6erGn0m commented on ktor-network/jvm/test/io/ktor/network/sockets/tests/ClientSocketTest.kt
> +                        ActorSelectorManager(Dispatchers.IO)
This should be closed explicitly. I know we had it before, but would be nice to fix once you are changing the test

2021-02-12 13:27 UTC, cy6erGn0m commented on ktor-network/jvm/test/io/ktor/network/sockets/tests/ClientSocketTest.kt
> +                } catch (e: ClosedChannelException) {
`e` -> `cause` or `ignored` or even `_`

2021-02-12 13:51 UTC, Ololoshechkin requested changes
Please, try using multiple ports but not a single one that may occasionally be taken.

2021-02-14 08:53 UTC, Stexxe commented
We could use some mocking framework to avoid writing boilerplate code.

### Note about the fix

There are two problems with the code that fixes the self-connection problem:
1. The author assumes that the client passes a socket created from the channel and therefore closes the socket instead of the channel but it's possible to pass any socket to the `SocketImpl` constructor. If the socket isn't bound to the channel and the self-connection condition is true then the `while` loop inside `connect` method will go forever.
2. If a client encounters a self-connection problem the `ClosedChannelException` will be thrown without the actual reason why that's happened.

2021-02-17 07:51 UTC, cy6erGn0m approved these changes

2021-02-17 08:04 UTC, e5l approved these changes

2021-02-17 10:47 UTC, Ololoshechkin approved these changes
Please, try using multiple ports but not a single one that may occasionally be taken.

2021-02-17 11:38 UTC, merged