CORS origin validation
ktorio/ktor pull request #2377
Opened 2021-03-03 10:21 UTC by Stexxe

https://youtrack.jetbrains.com/issue/KTOR-469

2021-03-04 10:01 UTC, cy6erGn0m requested changes

2021-03-04 10:09 UTC, Stexxe commented on ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt
> +        allowSameOrigin && isSameOrigin(origin, point) -> OriginCheckResult.TerminateSteps
That's how it was before. I just extract it in the method.

2021-03-04 10:12 UTC, Stexxe commented on ktor-server/ktor-server-core/jvm/src/io/ktor/features/CORS.kt
> +    OK, TerminateSteps, Failed
Maybe, but I took this vocabulary from the spec https://www.w3.org/TR/2020/SPSD-cors-20200602/#resource-requests

2021-03-09 10:06 UTC, cy6erGn0m approved these changes

2021-03-09 10:22 UTC, merged