KTOR-2468 New routing resolve algorithm
ktorio/ktor pull request #2425
Opened 2021-04-15 20:55 UTC by rsinukov

todo

2021-04-18 07:54 UTC, cy6erGn0m requested changes
Looks good in general. We introduce a little bit more overhead because of extra allocations for lists but it seems to be difficult to eliminate.

2021-04-18 07:54 UTC, cy6erGn0m commented on ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RouteSelector.kt
> +         * Route evaluation succeeded for a transparent value
This needs a clarification what exactly "transparent" means, an example or something

2021-04-18 07:54 UTC, cy6erGn0m commented on ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt
> +        @Deprecated("Binary compatibility")
Fix comment to describe that it will become internal and instantiation this class will be no longer allowed

2021-04-18 07:54 UTC, cy6erGn0m commented on ktor-server/ktor-server-core/jvm/src/io/ktor/routing/RoutingResolve.kt
> +            .fold(ParametersBuilder()) { acc, result -> acc.apply { appendAll(result.parameters) } }
```suggestion
            .fold(ParametersBuilder()) { builder, result -> builder.appendAll(result.parameters) }
```

2021-04-22 08:37 UTC, e5l requested changes
Do we have the issue with the algorithm described first? I'm not sure that I can verify it directly in the source code. I would like to see the specification first

2021-04-26 20:20 UTC, rsinukov commented
@e5l The main issue is described in the PR description. It started to cause problems with the addition of a `TrailingSlashSelector` that can be in the middle of the route and matches almost everything with constant value.

2021-05-13 09:37 UTC, e5l approved these changes
LGTM as discussed, should we also make a topic in docs with an explanation of different cases?

2021-05-14 13:54 UTC, rsinukov commented
@e5l yes, I have a ticket to document the final algorithm

2021-05-17 14:32 UTC, cy6erGn0m approved these changes

2021-05-17 21:55 UTC, merged