KTOR-572 Retry on HttpCode or network error
ktorio/ktor pull request #2574
Opened 2021-08-11 12:42 UTC by rsinukov

2021-09-15 09:37 UTC, e5l requested changes
LGTM, 
@hhariri could you check the public API docs?

2021-09-15 09:37 UTC, e5l commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
> +                    val retry = retryCount < maxRetries && shouldRetry(call.request, call.response)
I would extract the condition in a separate method

2021-09-15 09:37 UTC, e5l commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
> +    private var maxRetries: Int = configuration.maxRetries
`var` -> `val`

2021-09-16 09:12 UTC, andreyaksenov requested changes

2021-09-16 09:12 UTC, andreyaksenov commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
> +         */
> Specifies an exponential delay between retries, which is calculated using the [Exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) algorithm.

2021-09-16 09:12 UTC, andreyaksenov commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
> +         */
> A function that waits for the specified amount of milliseconds. ...

2021-09-16 09:12 UTC, andreyaksenov commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
> + */
> Configures the [HttpRequestRetry] plugin on a per-request level.

2021-09-16 12:14 UTC, rsinukov commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/HttpRequestRetry.kt
> + * Plugin that provides retry functionality. Default retry policy is no retry.
Updated. Yes, default means no configuration

2021-09-16 12:40 UTC, e5l approved these changes

2021-09-16 13:15 UTC, andreyaksenov approved these changes

2021-09-16 13:27 UTC, merged