KTOR-3539 Migrate server plugins to multiplatform
ktorio/ktor pull request #2725
Opened 2021-12-08 17:14 UTC by rsinukov

2022-01-25 06:05 UTC, olme04 commented on ktor-server/ktor-server-plugins/ktor-server-caching-headers/jvmAndNix/src/io/ktor/server/plugins/cachingheaders/CachingHeaders.kt
> +public class CachingHeadersConfiguration {
`CachingHeadersConfiguration` -> `CachingHeadersConfig`

2022-01-25 09:12 UTC, e5l requested changes

2022-01-25 09:12 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/test/io/ktor/tests/CORSTest.kt
> +                get() = throw Exception("Not implemented")
Consider using `TODO("Is not supported in mock implementation")`

2022-01-25 09:12 UTC, e5l commented on ktor-server/ktor-server-tests/jvmAndNix/test/io/ktor/tests/server/application/ApplicationEventTest.kt
> +    fun checkingTheNumberOfCallsToApplicationStopPreparingUseWithTestApplication() {
could we rename these tests?

2022-01-25 09:13 UTC, e5l commented
Consider checking `lift` build

2022-01-25 13:30 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-cors/jvmAndNix/test/io/ktor/tests/CORSTest.kt
> +                get() = throw Exception("Not implemented")
@sonatype-lift ignore

2022-01-25 13:30 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-auth/jvmAndNix/src/io/ktor/server/auth/BasicAuth.kt
>              } catch (e: Throwable) {
@sonatype-lift ignore

2022-01-25 16:41 UTC, rsinukov commented on ktor-io/js/src/io/ktor/utils/io/charsets/CharsetJS.kt
> +        if (this::class != other::class) return false
wow, auto generated equals is weird. good catch

2022-01-26 09:34 UTC, e5l approved these changes

2022-01-26 14:12 UTC, merged