Daria/attr equals
ktorio/ktor pull request #2731
Opened 2021-12-10 11:49 UTC by lolilofit

Ticket: [KTOR-3538](https://youtrack.jetbrains.com/issue/KTOR-3538)

**Solution**
Add `equals` and `hashCode` to the `AttributeKey` class.
Deprecate `EquatableAttributeKey`

2021-12-10 13:17 UTC, rsinukov requested changes

2021-12-10 13:17 UTC, rsinukov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
> +@Deprecated("Please use `AttributeKey` class instead")
Please replace internal usages of this class

2021-12-11 09:45 UTC, olme04 commented
Maybe it's better to make `EquatableAttributeKey` a deprecated typealias for `AttributeKey`?
And as we a here, I would propose to add check in `init` that name isn't blank (`require(name.isNotBlank())`) and adapt `toString` according this change. Now, as all keys are the same based on key, there is no any sense to have possibility to specify blank name

2021-12-13 12:24 UTC, lolilofit commented
> Maybe it's better to make `EquatableAttributeKey` a deprecated typealias for `AttributeKey`? And as we a here, I would propose to add check in `init` that name isn't blank (`require(name.isNotBlank())`) and adapt `toString` according this change. Now, as all keys are the same based on key, there is no any sense to have possibility to specify blank name

@olme04 
Thanks for your comment! I've added name check in init and referenced to the `AttributeKey` in `EquatableAttributeKey` with replaceWith

2021-12-13 12:29 UTC, olme04 commented
@lolilofit and what about typealias instead of `open class` and inheriting? Now, both classes are fully identical in implementation.

2021-12-13 12:57 UTC, rsinukov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
> +        if(name.isEmpty()) {
Please fix formatting here

2021-12-13 13:08 UTC, rsinukov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
>  public open class AttributeKey<T>(public val name: String) {
While you are here, can you please change the type of `<T>` to `<T : Any>`? `Attributes` class uses this restriction

2021-12-14 07:22 UTC, lolilofit commented
> @lolilofit and what about typealias instead of `open class` and inheriting? Now, both classes are fully identical in implementation.

@olme04 
I've added typealias with new commits. Thanks for the help!

2021-12-14 11:29 UTC, lolilofit commented
@andreyaksenov, please could you check public API?

2021-12-14 11:42 UTC, andreyaksenov requested changes

2021-12-14 11:42 UTC, andreyaksenov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
> + * @param name is a name of the attribute for diagnostic purposes. Couldn't be blank
Couldn't be blank -> Can't be blank

2021-12-14 11:42 UTC, andreyaksenov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
> + * Version of [AttributeKey] that overrides [equals] and [hashCode] using [name]
Version -> A version

2021-12-14 11:42 UTC, andreyaksenov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
> + * @param T is type of the value stored in the attribute
is type -> is a type

2021-12-14 11:42 UTC, andreyaksenov commented on ktor-utils/common/src/io/ktor/util/Attributes.kt
>   * Create attributes instance suitable for the particular platform
> Creates an attributes instance ...

2021-12-14 11:58 UTC, andreyaksenov approved these changes

2021-12-14 12:48 UTC, rsinukov approved these changes

2021-12-16 06:41 UTC, merged