KTOR-3650 Fixed `appendIfNameAbsent` and `appendIfNameAndValueAbsent`
ktorio/ktor pull request #2768
Opened 2022-01-07 15:36 UTC by rsinukov

2022-01-13 06:49 UTC, Stexxe commented on ktor-utils/common/src/io/ktor/util/StringValues.kt
> +    if (contains(name)) return@apply
Could you please just get rid of `return` since there is only one if statement?

2022-01-13 09:12 UTC, e5l commented
Hey, could you check failing test?

2022-01-13 09:14 UTC, e5l requested changes
please check the CI build

2022-01-18 09:16 UTC, e5l approved these changes
lgtm

2022-01-18 14:48 UTC, merged