KTOR-3656 Use secure random for nonce generation
ktorio/ktor pull request #2776
Opened 2022-01-17 13:53 UTC by rsinukov

2022-01-18 09:15 UTC, e5l requested changes
Could you check the compilation error for benchmarks?

https://ktor.teamcity.com/buildConfiguration/Ktor_AllocationTests/62594?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true

2022-01-28 09:11 UTC, rsinukov commented
Hi @danwallach 
Thanks for your comments. This PR is still in draft and I opened it just for checking that it works on different platform and OS. I'll address your comments before merging.

2022-03-03 14:18 UTC, e5l approved these changes
lgtm

2022-03-07 12:17 UTC, rsinukov commented on ktor-utils/js/src/io/ktor/util/CryptoJs.kt
> +private const val NONCE_SIZE_IN_BYTES = 16
please extract to common internal constant

2022-03-10 11:15 UTC, merged

2022-03-10 16:29 UTC, danwallach commented
Feature request: expose the `secureRandom` method (currently `internal expect fun secureRandom(bytes: ByteArray)`) as a public part of the API. This would make it useful for applications, like mine, that need a portable way to get secure random bytes, for their own cryptographic needs.