KTOR-3667 Rewrite WebJars plugin to new API
ktorio/ktor pull request #2799
Opened 2022-01-26 10:54 UTC by Ololoshechkin

https://youtrack.jetbrains.com/issue/KTOR-3667

2022-01-27 05:27 UTC, olme04 commented on ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt
> +    public var zone: ZoneId = ZoneId.systemDefault()
may be drop it now? as it's 2.0?

2022-01-27 09:09 UTC, e5l requested changes

2022-01-27 09:09 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt
> +private fun extractWebJar(path: String, knownWebJars: Set<String>, locator: WebJarAssetLocator): String {
consider extracting public API to the separate file to make it easier to inspect

2022-01-27 09:09 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt
> +                    call.respond(
Could you add the test when the call is already handled by a different plugin before `Webjars`?

2022-01-27 12:11 UTC, Ololoshechkin commented on ktor-server/ktor-server-plugins/ktor-server-webjars/jvm/src/io/ktor/server/webjars/Webjars.kt
> +    public var zone: ZoneId = ZoneId.systemDefault()
Will drop, thanks

2022-01-30 22:35 UTC, rsinukov approved these changes

2022-01-31 08:55 UTC, e5l approved these changes
Good job, lgtm

2022-02-02 15:21 UTC, merged