KTOR-3721 KTOR-3707 Status pages Fixes
ktorio/ktor pull request #2810
Opened 2022-01-27 14:27 UTC by e5l

Verify [KTOR-3721](https://youtrack.jetbrains.com/issue/KTOR-3721)
Verify [KTOR-3707](https://youtrack.jetbrains.com/issue/KTOR-3707)

2022-01-27 16:46 UTC, rsinukov requested changes
Please check CI build

2022-01-27 16:46 UTC, rsinukov commented on ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Routing.kt
> +        println("Resolve finished: $resolveResult")
Please remove `println`

2022-01-27 16:46 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/src/io/ktor/server/plugins/statuspages/StatusPages.kt
> + * Specify how the exception should be handled.
`Specifies`

2022-01-27 16:46 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/test/io/ktor/server/plugins/statuspages/StatusPageTest.kt
> +    fun testStatusPagesNotCalledAfterRouting() {
`testRoutingNotCalledAfterStatusPages`

2022-01-27 17:37 UTC, e5l commented on ktor-server/ktor-server-core/jvmAndNix/src/io/ktor/server/routing/Routing.kt
> +        println("Resolve finished: $resolveResult")
Thanks, will do

2022-01-27 17:37 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/test/io/ktor/server/plugins/statuspages/StatusPageTest.kt
> +    fun testStatusPagesNotCalledAfterRouting() {
Exactly, will rename

2022-01-31 16:46 UTC, rsinukov approved these changes

2022-01-31 16:46 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-status-pages/jvmAndNix/test/io/ktor/server/plugins/statuspages/StatusPagesTest.kt
> +        testApplication {
please use `testErrorShouldNotRecurse() = testApplication` syntax

2022-02-01 07:45 UTC, merged