KTOR-3677 Update (X)ForwardedHeaders to new API
ktorio/ktor pull request #2816
Opened 2022-01-28 10:11 UTC by hhariri

Update (X)ForwardedHeaders to new API

2022-01-28 14:49 UTC, rsinukov requested changes

2022-01-28 14:49 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/ForwardedHeaders.kt
> +        val forwardedParsedKey: AttributeKey<List<ForwardedHeaderValue>> =
It should be top level public property, so that users can read the value using this key

2022-01-28 14:49 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/ForwardedHeaders.kt
> +
extra empty line, checkstyle will fail here

2022-01-28 14:49 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/ForwardedHeaders.kt
> +        onCall { call ->
This callback is invoked too late. Logging, monitoring and some other plugins will be executed with unmodified value. Consider creating a hook for `Setup` phase

2022-01-28 14:49 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/ForwardedHeaders.kt
> +        onCall { call ->
Same comment for other plugin

2022-02-01 08:06 UTC, e5l requested changes
LGTM in general, please address minor issues

2022-02-01 08:06 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/ForwardedHeaders.kt
> +    public var forwardedHeadersHandler: (MutableOriginConnectionPoint, List<ForwardedHeaderValue>) -> Unit =
Consider avoiding having public API with `var` lambdas. It's hard to track compatibility and migrate them: adding or changing parameter starts being hard to migrate breaking change

2022-02-01 08:06 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/XForwardedHeaders.kt
> +    public val hostHeaders: ArrayList<String> = arrayListOf(HttpHeaders.XForwardedHost, HttpHeaders.XForwardedServer)
Could you tell me why the type `ArrayList` is required here?

2022-02-01 08:06 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/XForwardedHeaders.kt
> +public val XForwardedHeaders: ApplicationPlugin<Application, XForwardedHeadersConfig, PluginInstance> =
I would also keep `XForwardedHeaderSupport` without implementation, but with `@Deprecated` and `replaceWith`

2022-02-04 06:14 UTC, e5l approved these changes
lgtm

2022-02-04 06:15 UTC, e5l commented
please also rebase it on the `new-plugins-eap`

2022-02-07 09:46 UTC, e5l approved these changes
lgtm

2022-02-07 09:46 UTC, e5l commented
please check the CI

2022-02-07 13:50 UTC, rsinukov approved these changes

2022-02-07 13:50 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-forwarded-header/jvmAndNix/src/io/ktor/server/plugins/forwardedheaders/ForwardedHeaders.kt
> +public class ForwardedHeadersConfig {
Please add `@KtorDsl` annotation that was merged to the main branch today.

2022-02-09 15:14 UTC, merged