WIP
ktorio/ktor pull request #2987
Opened 2022-05-05 11:51 UTC by e5l

**Subsystem**
Client/Server, related modules

**Motivation**
Describe what problem this PR solves and why it is important. Refer to a bug/ticket #.

**Solution**
Describe your solution.

2022-05-11 06:16 UTC, e5l commented on ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/Endpoint.kt
> +        } catch (cause: Throwable) {
@sonatype-lift ignore

2022-05-11 06:16 UTC, e5l commented on ktor-client/ktor-client-cio/jvmAndNix/src/io/ktor/client/engine/cio/Endpoint.kt
>          } catch (cause: Throwable) {
@sonatype-lift ignore

2022-05-12 12:41 UTC, rsinukov requested changes

2022-05-12 12:41 UTC, rsinukov commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt
> +class HttpTimeoutTest : ClientLoader(timeoutSeconds = 1000000) {
probably not intended

2022-05-12 12:41 UTC, rsinukov commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt
> -    fun testConnectTimeout() = clientTests(listOf("Js", "Darwin", "CIO")) {
does it make sense to rewrite them to use local server?

2022-05-13 06:38 UTC, e5l commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/HttpTimeoutTest.kt
> +class HttpTimeoutTest : ClientLoader(timeoutSeconds = 1000000) {
Thanks, fixed

2022-05-13 06:49 UTC, e5l commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingMockedTests.kt
> -    fun testLogResponseWithException() = testWithEngine(MockEngine) {
accidentally, fixed one more issue. thanks

2022-05-13 06:50 UTC, e5l commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/LoggingTest.kt
> -    fun testLogRedirect() = clientTests(listOf("js", "Curl", "CIO", "Java")) {
cause responses can be logged in any order

2022-05-13 06:51 UTC, e5l commented on ktor-io/api/ktor-io.api
> -	public final fun setClosedCause (Ljava/lang/Throwable;)V
It looks like an internal bridge, will check

2022-05-13 06:51 UTC, e5l commented on ktor-io/common/src/io/ktor/utils/io/core/BufferFactory.kt
> +            "Buffer size mismatch. Expected: $bufferSize, actual: ${instance.memory.size}"
It doesn't matter in this case, will use size everywhere

2022-05-13 06:53 UTC, e5l commented on ktor-utils/posix/src/io/ktor/util/CoroutineUtils.kt
> +        kotlin.runCatching {
it should be in the origin task

2022-05-13 07:19 UTC, e5l commented on ktor-io/api/ktor-io.api
> -	public final fun setClosedCause (Ljava/lang/Throwable;)V
Fixed

2022-05-13 13:55 UTC, rsinukov approved these changes

2022-05-16 06:45 UTC, merged