Fix DefaultJson to ignore unknown keys
ktorio/ktor pull request #3021
Opened 2022-05-24 18:48 UTC by FranAguilarRod

**Subsystem**
Client

**Motivation**
The documentation says that the JSON configuration is "mode is not strict so extra json fields are ignored" but is not what is actually doing.

**Solution**
Add `ignoreUnknownKeys = true` to make the JSON configuration work as expected.

2022-05-24 19:47 UTC, rsinukov commented
I'm not sure about this change. It will break the behaviour of existing clients and we better postpone it to majot release. Maybe it's better to fix documentation to reflect an actual behavior?

2022-05-25 10:17 UTC, FranAguilarRod commented
I agree, I just update the PR to fix the documentation and also add a test to prove the behavior

2022-05-25 13:17 UTC, rsinukov approved these changes
LGTM

2022-05-25 13:55 UTC, rsinukov requested changes

2022-05-26 10:06 UTC, FranAguilarRod commented on ktor-shared/ktor-serialization/ktor-serialization-kotlinx/ktor-serialization-kotlinx-json/common/test/JsonSerializationTest.kt
> +    @Test(expected = SerializationException::class)
Done ;)

2022-05-27 12:08 UTC, rsinukov approved these changes
LGTM

2022-05-27 12:08 UTC, merged