KTOR-4593 Add support to automatically use the correct translation file for Pebble based on Accept Language header
ktorio/ktor pull request #3086
Opened 2022-06-28 17:27 UTC by TreyBastian

**Subsystem**
Ktor-Server-Pebble

**Motivation**
This PR adds support for improving the ergonomics of using pebbles built in I18N support. It essentially makes it so you do not need to match Accept Headers to Locales in every route.

**Solution**
This uses a similar approach as the #1632 using `call.request.acceptLanguages` and validating it against a list of supported translations to either set the Locale or keep it `null` which is the default state.

2022-06-28 17:48 UTC, TreyBastian commented
What would the best way to update the docs for this be for once this is merged? There would be code snippets so would it be after a release?

2022-06-29 08:24 UTC, rsinukov requested changes
Thanks for the PR.
It's almost good to go, but minor comments. 
Regarding the docs, please create a ticket for this change in YouTrack, and we will make sure that it has proper docs after it's merged.

2022-06-29 08:24 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt
> +    public var availableLanguages: Array<String>? = null
Can you replace an array with a mutable list, please?

2022-06-29 08:24 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt
> +            engine.getTemplate(content.template).evaluate(writer, model, locale)
can you extract locale to `if/else` block and this line outside of it?

2022-06-29 08:24 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt
> +    public var availableLanguages: Array<String>? = null
Please add an API doc

2022-06-29 21:04 UTC, TreyBastian commented
> 

Thanks for reviewing. I made the changes I'll submit the YouTrack ticket in the morning. Let me know if there's anything else that should change. I've tried to stick with conventions I've seen in other plugins.

2022-06-30 08:30 UTC, TreyBastian commented
https://youtrack.jetbrains.com/issue/KTOR-4593/Allow-Pebble-to-use-Accepted-Language-header-for-built-in-i18n-support

2022-06-30 13:06 UTC, rsinukov requested changes
Couple more changes.

2022-06-30 13:06 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt
> +    public var availableLanguages: MutableList<String>? = null
Actually, it can be just `List` and not `MutableList`. Sorry =)

2022-06-30 13:06 UTC, rsinukov commented on ktor-server/ktor-server-plugins/ktor-server-pebble/jvm/src/io/ktor/server/pebble/Pebble.kt
> +        val availableLanguages: List<String>? = pluginConfig.availableLanguages?.toList()
please extract it to `createApplicationPlugin` to save the reference at install time to ignore possible mutations of config later

2022-07-06 08:19 UTC, TreyBastian commented
Sorry for the delay there those changes are in.

2022-07-06 10:21 UTC, rsinukov approved these changes
LGTM!
Will merge after CI run

2022-07-06 15:22 UTC, merged