KTOR-5405 allow booleans as multipart values
ktorio/ktor pull request #3336
Opened 2023-01-04 08:06 UTC by Rattenkrieg

**Subsystem**
Client multipart/form-data enhancement

**Motivation**
As per [KTOR-5405](https://youtrack.jetbrains.com/issue/KTOR-5405) there is desire to encode `Boolean` values the same way as `Number` values are encoded.

**Solution**
Wrapping `Boolean`s in `PartData.FormItem` which effectively puts quotes around string representation of the value.

2023-01-04 08:07 UTC, Rattenkrieg commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/ContentTest.kt
> +                append("world", true)
This test is actually annotated with `@Ignore`, I did a local run with annotation removed though.

2023-01-04 20:27 UTC, rsinukov requested changes
Thanks for the PR!
LGTM in general, but since this PR has a new API, can you please rebase it on top of `2.3.0-eap` branch, run `./gradlew apiDump` task and commit changes here?

2023-01-05 13:38 UTC, Rattenkrieg commented
@rsinukov thanks for the feedback, addressed.

2023-01-05 15:59 UTC, rsinukov approved these changes
LGTM
Will merge after CI check

2023-01-05 18:20 UTC, merged