Fix reading response of HEAD request
ktorio/ktor pull request #3438
Opened 2023-03-13 15:54 UTC by yassenb

**Subsystem**
client

**Motivation**
A lot of code has the same implementation handling all HTTP requests and this includes reading the body of a response. In the case of a HEAD request this can break when the Content-Length header has a non-zero value

**Solution**
Do not check the response length matches the Content-Length header for HEAD requests

2023-03-15 10:23 UTC, rsinukov requested changes
LGTM, but can you please add a test?

2023-03-15 10:44 UTC, yassenb commented
I thought about adding a test but I don't see where the tests for `DefaultTransform.kt` are, nor do I see an existing test for the functionality I'm changing (there should be a test that an `IllegalArgumentException` is raised when content length doesn't match the body length). My familiarity with the project is not good enough to dig deeper into the tests infrastructure so I would suggest either:
  * someone more familiar add a test
  * merge without a test

2023-03-22 12:51 UTC, rsinukov commented
There is a test for this transformation in `ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/DefaultTransformTest.kt`. You can add it there.

2023-03-29 22:59 UTC, rsinukov commented
I reopened this PR with the test added in #3465

2023-03-29 22:59 UTC, closed without merging