KTOR-2932 Fix cancelled and failed JS websockets not closing
ktorio/ktor pull request #3476
Opened 2023-04-06 13:12 UTC by Sejsel

**Subsystem**
Client, JS, Websockets

**Motivation**
Currently, websockets opened by the JS implementation in the browser do not get properly closed in case of cancellation or failure.

This is caused by browser `websocket.close()` throwing `InvalidAccessError` with codes that are not 1000 or 3000-4999 (see documentation [here](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close#exceptions)), the implementation used 1011.

This is also mentioned in KTOR-2932. This PR does not change the meaning of cancellations which is the main focus of KTOR-2932, it only addresses the major bug.

The websockets staying open can cause critical performance issues (and has caused them for us, exhausting websockets in nginx).

**Solution**
Use 1000 as the closing reason code in the JS implementation, it is likely the only reasonable option as using something from the 3000-4999 range would be unexpected.

2023-04-06 15:22 UTC, rsinukov requested changes
Thanks for the PR. Can you please add test for this fix?

2023-04-26 11:06 UTC, Sejsel commented
> Thanks for the PR. Can you please add test for this fix?

I am sorry, I do not currently have the time to implement tests for this.

Running any tests locally always fails with the default configuration. There also do not seem to be any related tests that I could easily modify for this, so I do not even know where tests for this would go.

I could not even find how to enable highlighting in the changed file for a while (changing `ktor.ide.jvmAndCommonOnly` to false in `gradle.properties` worked, but it doesn't seem to be documented anywhere, the CONTRIBUTING.md guide is fairly limited and I could not find any other documentation on the build process for this project).

2023-04-26 12:27 UTC, rsinukov commented
That's fair. I'll take it from here. Thanks again!

2023-05-02 16:32 UTC, rsinukov approved these changes

2023-05-02 16:32 UTC, merged

2023-05-03 00:03 UTC, Sejsel commented
@rsinukov, thank you for finishing this!