KTOR-5688 Make NSURLSessionDelegate constructor public
ktorio/ktor pull request #3660
Opened 2023-06-22 11:06 UTC by e5l

2023-06-22 17:43 UTC, marychatte approved these changes
lgtm

2023-06-27 12:39 UTC, rsinukov requested changes
I think it's ok to make constructor public and delete factory functions. But I would prefer to keep everything else internal or private

2023-07-04 08:20 UTC, rsinukov approved these changes
LGTM, but minot comments

2023-07-04 08:20 UTC, rsinukov commented on ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/KtorLegacyNSURLSessionDelegate.kt
> +public class KtorLegacyNSURLSessionDelegate(
factory function can be removed, if you add default parameter

2023-07-04 08:20 UTC, rsinukov commented on ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyTaskHandler.kt
> +public class DarwinLegacyTaskHandler(
why do other classes need to be public?

2023-07-05 07:28 UTC, e5l commented on ktor-client/ktor-client-darwin-legacy/darwin/src/io/ktor/client/engine/darwin/internal/legacy/DarwinLegacyTaskHandler.kt
> +public class DarwinLegacyTaskHandler(
thanks, fixed

2023-07-05 13:50 UTC, merged