KTOR-5963 CIO support for SSE plugin
ktorio/ktor pull request #3661
Opened 2023-06-23 14:47 UTC by marychatte

[KTOR-5963](https://youtrack.jetbrains.com/issue/KTOR-5963) 
[Design](https://youtrack.jetbrains.com/issue/KTOR-5938)

2023-07-25 17:32 UTC, rsinukov requested changes
Great work! Some comments

2023-07-25 17:32 UTC, rsinukov commented on ktor-client/ktor-client-okhttp/build.gradle.kts
> +            implementation(project(":ktor-client:ktor-client-plugins:ktor-client-sse"))
it's a bit strange that client engine depends on the plugin. should it be split?

2023-07-27 09:23 UTC, marychatte commented on ktor-client/ktor-client-plugins/ktor-client-sse/build.gradle.kts
> +    jsTest {
They are added in `ktor-client/ktor-client-plugins/build.gradle.kts` via subprojects config

2023-07-27 09:23 UTC, marychatte commented on ktor-client/ktor-client-plugins/ktor-client-sse/common/src/io/ktor/client/plugins/sse/DefaultClientSSESession.kt
> +        launch {
I guess not, thanks!

2023-07-27 17:01 UTC, marychatte commented on buildSrc/src/main/kotlin/test/server/tests/ServerSentEvents.kt
> +                call.respondBytesWriter(contentType = ContentType.Text.EventStream) {
because I need to specify `ContentType.Text.EventStream`

2023-07-31 13:22 UTC, rsinukov approved these changes
lgtm

2023-07-31 13:22 UTC, rsinukov commented on ktor-client/ktor-client-core/common/src/io/ktor/client/plugins/sse/DefaultClientSSESession.kt
> +            if (event.isCommentsEvent() && !showCommentEvents) {
i'll do it in one line without `{}`, but not a big deal

2023-07-31 13:22 UTC, rsinukov commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/SSESessionParserTest.kt
weird, why is it a binary file?

2023-07-31 14:13 UTC, marychatte commented on ktor-client/ktor-client-tests/common/test/io/ktor/client/tests/plugins/SSESessionParserTest.kt
I don't know, I thought it was bug

2023-07-31 16:07 UTC, merged