Update Gradle version to 8
ktorio/ktor pull request #3662
Opened 2023-06-27 07:20 UTC by e5l

2023-06-28 09:52 UTC, rsinukov requested changes
Please check CI

2023-06-28 09:52 UTC, rsinukov commented on buildSrc/build.gradle.kts
> +//kotlin {
why commented?

2023-07-06 07:29 UTC, e5l commented on buildSrc/build.gradle.kts
> +//kotlin {
fixed

2023-07-07 09:28 UTC, rsinukov commented
Please rebase

2023-07-07 09:30 UTC, e5l commented
done

2023-07-07 09:32 UTC, rsinukov approved these changes
LGTM, but please wait for the CI to run

2023-07-13 06:58 UTC, merged

2023-08-08 09:31 UTC, hfhbd commented on buildSrc/build.gradle.kts
> +    id("org.gradle.kotlin.kotlin-dsl") version "4.0.14"
you should not set this version explicitly, but use `kotlin-dsl`. the same for `plugin-serialization` should use `embeddedKotlinVersion`.

2023-08-08 09:33 UTC, hfhbd commented
Did you also run the task twice? The wrapper wasn't update too. Wanna have a PR?

2023-08-08 09:37 UTC, e5l commented
Strange, will take a look