KTOR-5540 Fix darwin ws pong message
ktorio/ktor pull request #3747
Opened 2023-09-08 13:52 UTC by e5l

Fix [KTOR-5540](https://youtrack.jetbrains.com/issue/KTOR-5540)

2023-09-08 14:27 UTC, vitorhugods commented on ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
> +    fun testWebSocketPinInterval() = testSuspend {
```suggestion
    fun testWebSocketPingInterval() = testSuspend {
```

2023-09-08 16:59 UTC, rsinukov requested changes

2023-09-08 16:59 UTC, rsinukov commented on ktor-client/ktor-client-darwin/darwin/test/DarwinEngineTest.kt
> +        client.webSocket("wss://ws.postman-echo.com/raw") {
lets add a route to our test server and not rely on 3rd patry

2023-09-11 09:38 UTC, rsinukov approved these changes

2023-09-11 10:27 UTC, merged