KTOR-6447 Update Kotlin to 1.9.20
ktorio/ktor pull request #3817
Opened 2023-11-08 09:57 UTC by e5l

Fix [KTOR-6447](https://youtrack.jetbrains.com/issue/KTOR-6447/Update-Kotlin-to-1.9.20)

2023-11-08 12:01 UTC, rsinukov requested changes

2023-11-09 11:58 UTC, e5l commented on build.gradle.kts
> +            dokkaPlugin("org.jetbrains.dokka:versioning-plugin:1.9.10")
dokka 1.9.20 is not released yet

2023-11-09 11:58 UTC, e5l commented on gradle.properties
> +ktor.ide.jvmAndCommonOnly=false
nope, will revert

2023-11-09 11:59 UTC, e5l commented on gradle.properties
> +# org.gradle.configuration-cache=true
thanks, will drop, it's not compatible anyway

2023-11-09 11:59 UTC, e5l commented on ktor-network/nix/src/io/ktor/network/sockets/SocketAddressNative.kt
> +public actual class InetSocketAddress actual constructor(
Thanks, will add

2023-11-09 13:41 UTC, rsinukov approved these changes

2023-11-10 08:54 UTC, merged

2023-11-22 15:53 UTC, IgnatBeresnev commented
Since Dokka was updated to 1.9.10, JFYI this workaround is no longer needed and can be removed

https://github.com/ktorio/ktor/blob/b4a2f0730d0de4e95a7c9f6beac16f7b8dc479f4/gradle.properties#L37-L39

cc @rsinukov @e5l

2023-11-24 08:48 UTC, e5l commented
Thanks, will update.