KTOR-7254 Fix for IOException on concurrent requests using request body limit
ktorio/ktor pull request #4194
Opened 2024-08-06 13:30 UTC by bjhham

**Subsystem**
Server, Body Limit

**Motivation**
[KTOR-7254](https://youtrack.jetbrains.com/issue/KTOR-7254) IOException: startIndex (0) > endIndex (-1) when making concurrent requests via thread pool

**Solution**
It's possible for the request to close between the check for `isClosedForRead` and `readAvalailable`, which results in `-1` being returned, which causes the `writeFully` to blow up.

2024-08-06 16:26 UTC, e5l requested changes
Could we have a unit test for the case?

2024-08-07 06:46 UTC, bjhham commented
Hmm I didn't include one because the only way to reproduce it was spamming it with a ton of parallel requests.  Do you have any ideas on how it could be reproduced reliably?

2024-08-07 06:48 UTC, e5l commented on ktor-server/ktor-server-plugins/ktor-server-body-limit/common/src/io/ktor/server/plugins/bodylimit/RequestBodyLimit.kt
> -                    content.awaitContent()
We can try extracting the plugin block into a function and provide the mock content

2024-08-07 06:49 UTC, e5l commented
We can try extracting the plugin block into a function and provide the mock content

2024-08-07 12:19 UTC, e5l approved these changes

2024-08-14 11:07 UTC, merged