KTOR-6412: add AcceptEncoding constants
ktorio/ktor pull request #4217
Opened 2024-08-15 16:45 UTC by anton-erofeev

**Subsystem**
http

**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-6412

**Solution**
Added Accept Encoding constants

2024-08-21 11:05 UTC, e5l commented
@marychatte, could you please check?

2024-08-21 14:39 UTC, marychatte requested changes
Thanks for PR!
It's a good idea to add constants! Maybe we can use `HeaderValueWithParameters` as it's done already with [`ContentType`](https://github.com/ktorio/ktor/blob/1eeb7c11c93ad1cce550c71df1a189d22c74148f/ktor-http/common/src/io/ktor/http/ContentTypes.kt#L14). Because it is also can be a parameter [;q=](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding#q) (qvalues weighting). And please add Kdoc and some tests

2024-08-26 18:36 UTC, anton-erofeev commented
> Thanks for PR! It's a good idea to add constants! Maybe we can use `HeaderValueWithParameters` as it's done already with [`ContentType`](https://github.com/ktorio/ktor/blob/1eeb7c11c93ad1cce550c71df1a189d22c74148f/ktor-http/common/src/io/ktor/http/ContentTypes.kt#L14). Because it is also can be a parameter [;q=](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding#q) (qvalues weighting). And please add Kdoc and some tests

Hi @marychatte!
I updated the PR with review points fixes, could you please take a look?

2024-09-04 13:25 UTC, marychatte reviewed
@anton-erofeev Good work on the PR! Thank you a lot
I added a few comments, but in general I think everything is good!

2024-09-12 09:52 UTC, merged