issue/ktor 7470 receiveMultipart throw UnsupportedMediaTypeException
ktorio/ktor pull request #4339
Opened 2024-09-25 04:13 UTC by stokado

**Subsystem**
Server, related modules

**Motivation**
Return 415 Unsupported Media-Type if client passed the wrong Content-Type header or didn't pass any value at all. KTOR-7470

**Solution**
Given no Content-Type header, throw UnsupportedMediaTypeException with corresponding message.
Given bad Content-Type header, rethrow UnsupportedMediaTypeException.

2024-10-07 05:41 UTC, e5l commented
@marychatte, could you check?

2024-10-10 11:36 UTC, marychatte requested changes
Thanks for the PR, please check the comments

2024-10-10 11:36 UTC, marychatte commented on ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt
> +        ?: throw UnsupportedMediaTypeException(null)
There is also one more place, where exception is thrown - CIO: 
1)https://github.com/ktorio/ktor/blob/58d1714e5dadfe446430a492ac739c1058f84601/ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt#L141
2)https://github.com/ktorio/ktor/blob/58d1714e5dadfe446430a492ac739c1058f84601/ktor-http/ktor-http-cio/jvm/src/io/ktor/http/cio/Multipart.kt#L158
Can we please fix it too?

2024-10-10 12:28 UTC, stokado commented on ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt
> +    } catch (_: IOException) {
We do not have an access to UnsupportedMediaTypeException in CIO module

I had to catch an exception on the server and rethrow it here, it is the latest server code before CIO module

This should answer this [question](https://github.com/ktorio/ktor/pull/4339#discussion_r1795252021)

2024-10-10 17:21 UTC, marychatte commented on ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt
> +    } catch (_: IOException) {
Thanks. Can we add a check that the exception message contains "Content-Type " because another IOException also thrown

2024-10-11 06:04 UTC, stokado commented on ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt
> +    } catch (_: IOException) {
I've added this check, but maybe there could be a way to add `UnsupportedMediaTypeException` to CIO module or create separate Exception for the Unsupported Media errors in CIO?

Not sure  if it is a common practice to define catch logic based on exception's message

2024-10-29 11:15 UTC, marychatte commented on ktor-server/ktor-server-core/jvm/src/io/ktor/server/engine/DefaultTransformJvm.kt
> +    } catch (_: IOException) {
Unfortunately, adding `UnsupportedMediaTypeException` to CIO module is a breaking change so can we please create a new Exception in CIO module `UnsupportedMediaTypeExceptionCIO` and catch it in `DefaultTransformJvm`?

2024-11-12 12:49 UTC, stokado commented
> Сan we please create a new Exception in CIO module `UnsupportedMediaTypeExceptionCIO` and catch it in `DefaultTransformJvm`?

Of course, I will update the PR this week. I was not able to do it earlier :)

2024-11-18 15:18 UTC, marychatte approved these changes
Good work, thank you!
I just fixed codestyle and other minor issues; I will merge the PR after checks

2024-11-19 06:02 UTC, stokado commented on ktor-server/ktor-server-core/api/ktor-server-core.klib.api
> +    constructor <init>(io.ktor.http/ContentType?) // io.ktor.server.plugins/UnsupportedMediaTypeException.<init>|<init>(io.ktor.http.ContentType?){}[0]
I've added constructor with an old signature
How can I run an apiDump task now?

2024-11-19 12:42 UTC, marychatte commented on ktor-server/ktor-server-core/api/ktor-server-core.klib.api
> +    constructor <init>(io.ktor.http/ContentType?) // io.ktor.server.plugins/UnsupportedMediaTypeException.<init>|<init>(io.ktor.http.ContentType?){}[0]
We discussed it with @osipxd and it's binary compatible, I reverted the last commit and will merge the PR

2024-11-21 10:01 UTC, merged