KTOR-7586: improve parsing of supported media types
ktorio/ktor pull request #4410
Opened 2024-10-17 19:09 UTC by anton-erofeev

**Subsystem**
Core

**Motivation**
https://youtrack.jetbrains.com/issue/KTOR-7586

**Solution**
improved parsing of supported media types

2024-10-21 06:26 UTC, osipxd requested changes
Thank you for your contribution! 🚀 
I have some ideas on how to improve it. Please, check the comments.

2024-10-21 18:29 UTC, anton-erofeev commented on ktor-http/common/src/io/ktor/http/Mimes.kt
> +application/javascript,js
> after some separator

are you suggesting to insert a comment into `rawMimes` and ignore it when processing the string?

2024-10-21 19:25 UTC, osipxd commented on ktor-http/common/src/io/ktor/http/Mimes.kt
> +application/javascript,js
Yes, we could ignore lines starting with `#` in addition to already ignored empty lines

2024-10-22 18:48 UTC, anton-erofeev commented
> Thank you for your contribution! 🚀 I have some ideas on how to improve it. Please, check the comments.

good points, thanks, please review the fixes

2024-10-28 14:38 UTC, osipxd approved these changes
Thank you, this is a great job!
Just a few minor comments left

2024-10-29 09:34 UTC, osipxd commented
Than you, I'll merge this PR to 3.1.0-eap 🎉

2024-10-30 09:51 UTC, merged