KTOR-6501 Rewrite KDocs for HttpClient.close, HttpStatement, and Http…
ktorio/ktor pull request #4448
Opened 2024-11-04 10:46 UTC by e5l

2024-11-08 11:51 UTC, vnikolova requested changes
I noticed in some places elements weren't linked (see in comments, but there might be more). Otherwise looks great!

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/request/builders.kt
> + * [HttpClient.get], [HttpClient.post], HttpClient.put`, and `HttpClient.delete`, which are often more
```suggestion
 * [HttpClient.get], [HttpClient.post], [HttpClient.put], and [HttpClient.delete], which are often more
```

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/request/builders.kt
> + * [HttpClient.get], [HttpClient.post], HttpClient.put`, and `HttpClient.delete`, which are often more
Same as above.

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/request/builders.kt
> + * [HttpClient.get], [HttpClient.post], HttpClient.put`, and `HttpClient.delete`, which are often more
Same here.

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/request/builders.kt
> + * [HttpClient.get], [HttpClient.post], HttpClient.put`, and `HttpClient.delete`, which are often more
And here.

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt
> + * Represents a prepared HTTP request statement for `HttpClient`.
```suggestion
 * Represents a prepared HTTP request statement for [HttpClient].
```

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/statement/HttpStatement.kt
> + * The `HttpStatement` class encapsulates a request configuration without executing it immediately.
```suggestion
 * The [HttpStatement] class encapsulates a request configuration without executing it immediately.
```

2024-11-08 11:51 UTC, vnikolova commented on ktor-client/ktor-client-core/common/src/io/ktor/client/utils/CoroutineUtils.kt
> + * Creates [CoroutineDispatcher] for the client with fixed [threadCount] and specified [dispatcherName].
Here we can also use `@param` to describe `threadCount` and `dispatcherName` in the same way it is done in the other KDocs.

2024-11-11 09:36 UTC, e5l commented
Hey @vnikolova, thanks for the review. Let me check the comments!

2024-11-11 09:46 UTC, e5l commented
@vnikolova, fixed!

2024-11-12 10:25 UTC, vnikolova approved these changes

2024-11-12 10:26 UTC, merged