KTOR-7876 Fix Sink.writeText corrupts long streams for Jetty server
ktorio/ktor pull request #4526
Opened 2024-12-03 13:05 UTC by marychatte

**Subsystem**
Server
**Motivation**
[KTOR-7876 Jetty: respondBytesWriter with writeStringUtf8 corrupts long streams containing non-ascii chars](https://youtrack.jetbrains.com/issue/KTOR-7876)

2024-12-05 05:12 UTC, e5l requested changes

2024-12-05 05:12 UTC, e5l commented on ktor-io/common/src/io/ktor/utils/io/core/Strings.kt
> + * Writes [text] characters in range [fromIndex] .. [toIndex]) with the specified [charset]
Could you check the KDoc and mention explicitly included and excluded part of the ranges?

2024-12-05 05:12 UTC, e5l commented on ktor-io/common/src/io/ktor/utils/io/core/Strings.kt
> -        return writeString(text.toString(), fromIndex, toIndex)
Could you tell me why whiteStrings corrupts non ASCII? Should we log this to the kotlinx-io instead?

2025-07-30 13:21 UTC, marychatte commented
I rechecked the problem, it wasn't on the Ktor side, and this anomaly doesn't appear anymore

2025-07-30 13:21 UTC, closed without merging